version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: one_edu
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: one_edu_user
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:NnvsKEM58glbcBs0en6trcIrDBSyXh2nh+XpnjLAxjE=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=one_edu
      - DB_USERNAME=one_edu_user
      - DB_PASSWORD=password123
      - SANCTUM_STATEFUL_DOMAINS=localhost
      - SESSION_DOMAIN=localhost
      - CORS_ALLOWED_ORIGINS=http://localhost
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
      - backend_vendor:/var/www/html/vendor
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network


  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "80:80"   # FE served by Nginx
    depends_on:
      - backend
    networks:
      - app-network


volumes:
  mysql_data:
    driver: local
  backend_storage:
    driver: local
  backend_vendor:
    driver: local

networks:
  app-network:
    driver: bridge