name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**' # Memicu hanya jika ada perubahan di direktori backend
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Sesuaikan dengan versi PHP Anda
          extensions: mbstring, pdo_mysql, zip, xml # Tambahkan ekstensi yang dibutuhkan

      - name: Install Composer Dependencies
        working-directory: ./backend # Pastikan direktori kerja benar
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Build and Push Docker Image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Konteks build adalah direktori backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/one-education-backend:latest # Ganti nama image Anda