name: Laravel + React CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: one-edu
          MYSQL_ROOT_PASSWORD: password123
          MYSQL_USER: one-edu-user
          MYSQL_PASSWORD: password123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build & Push Backend
      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/one-edu-backend:latest

      # Build & Push Frontend
      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/one-edu-frontend:latest

      # (Optional) Test Laravel
      - name: Run Laravel Tests
        run: |
          docker compose -f docker-compose.yml run --rm backend php artisan test
